export const GET_AWSACCOUNTS = "GET_AWSACCOUNTS";
export const GET_ERRORS = "GET_ERRORS";
export const CREATE_MESSAGE = "CREATE_MESSAGE";
export const DELETE_AWSACCOUNT = "DELETE_AWSACCOUNT";
export const ADD_AWSACCOUNT = "ADD_AWSACCOUNT";
