# Generated by Django 3.0.6 on 2020-05-18 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awsoptimizer', '0002_auto_20200518_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awsoptimizer',
            name='accountid',
            field=models.IntegerField(unique=True),
        ),
    ]
